// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdvanceWaveReducer from "../advance_wave_reducer";
import DamagePlayerReducer from "../damage_player_reducer";
import HealPlayerReducer from "../heal_player_reducer";
import RegisterEnemyReducer from "../register_enemy_reducer";
import RegisterPlayerReducer from "../register_player_reducer";
import ReportEnemyKillReducer from "../report_enemy_kill_reducer";
import RespawnPlayerReducer from "../respawn_player_reducer";
import SetEntityTransformReducer from "../set_entity_transform_reducer";
import SetPlayerCharacterClassReducer from "../set_player_character_class_reducer";

export type AdvanceWaveParams = __Infer<typeof AdvanceWaveReducer>;
export type DamagePlayerParams = __Infer<typeof DamagePlayerReducer>;
export type HealPlayerParams = __Infer<typeof HealPlayerReducer>;
export type RegisterEnemyParams = __Infer<typeof RegisterEnemyReducer>;
export type RegisterPlayerParams = __Infer<typeof RegisterPlayerReducer>;
export type ReportEnemyKillParams = __Infer<typeof ReportEnemyKillReducer>;
export type RespawnPlayerParams = __Infer<typeof RespawnPlayerReducer>;
export type SetEntityTransformParams = __Infer<typeof SetEntityTransformReducer>;
export type SetPlayerCharacterClassParams = __Infer<typeof SetPlayerCharacterClassReducer>;

